services:
  api:
    build: .
    container_name: epias_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - USE_LOCAL_MODEL_ONLY=true
    volumes:
      - ./model.json:/app/model.json
